[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
BonitoBook = "b416d416-7a6e-4336-8c1a-1f8a8cd59518"
BonitoSites = "8b3cd1a5-63d9-421b-9fde-46b64b830918"

[sources]
Bonito = {rev = "sd/serialization-order", url = "https://github.com/SimonDanisch/Bonito.jl"}
BonitoBook = {path = ".."}
BonitoSites = {url = "https://github.com/SimonDanisch/BonitoSites.jl"}
